Exwm replace support
ch11ng/xelb pull request #19
Opened 2018-03-01 16:36 UTC by medranocalvo

XELB changes needed for `replace-support` EXWM branch.

Names are not great, please suggest better if possible. It might be useful to rename or alias `xcb:+event` to `xcb:+add-event` for similarity with `add-hook` and `remove-hook`.

2018-03-03 18:27 UTC, ch11ng commented
> It might be useful to rename or alias `xcb:+event` to `xcb:+add-event`.

The `+` in `xcb:+event` actually means 'add'.  `xcb:add-event` would be better.

2018-03-03 18:28 UTC, ch11ng requested changes

2018-03-03 18:28 UTC, ch11ng commented on xcb.el
> +;;   - `xcb:+remove-event'
Use `xcb:remove-event`.

2018-03-03 18:28 UTC, ch11ng commented on xcb.el
> +Note that event listeners attached this way are shared with the super- and sub-
This docstring is no longer relevant.

2018-03-03 18:28 UTC, ch11ng commented on xcb.el
> +  "Return t when the connection OBJ has extension data for NAMESPACE."
No need to convert the result to `t`.

2018-03-05 16:06 UTC, medranocalvo commented
Thanks for the review.  Addressed the issues you noted.

Additionally, renamed `xcb:+event` to `xcb:add-event` and added the former as obsolete alias; let me know whether that's all right.

2018-03-05 16:30 UTC, ch11ng commented
Sorry but now that there is no use for `xcb:remove-event` (see the review on the other PR) perhaps we can just drop the changes on `xcb:+event` (the naming is admittedly not good but it's get used too much) and `xcb:remove-event`? Everything else looks fine to me.

PS.  I have no idea but some of my original reviews seem get lost.  This implementation of `xcb:remove-event` can't handle XGE and XKB events.

2018-03-05 17:07 UTC, medranocalvo commented
I didn't receive your comments w.r.t. XGE and XKB; you were right about it.
I think that being able to stop listening to events would be useful for XELB applications other than EXWM. Note that the old changes preserved the `xcb:+event` function as an alias.
I have removed those changes, along with `xcb:got-extension-data-p` which is not needed for replace support either.

2018-03-07 17:05 UTC, merged